# vim: ts=2 sw=2 et

# On every push, and on every PR, do come checks.
#
# We do the following things:
# * Run CodeQL

name: Run CodeQL 

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  codeql:
    name: Run CodeQL on ubuntu-latest & Python 3.13
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - name: Install non-Python dependencies (Ubuntu)
      run: |
        true

    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install dependencies for testing
      run: |
        pip install .

    - name: CodeQL Init
      uses: github/codeql-action/init@fe4161a26a8629af62121b670040955b330f9af2
      with:
        languages: python

    - name: CodeQL Analyze
      uses: github/codeql-action/analyze@fe4161a26a8629af62121b670040955b330f9af2
      with:
        category: "/language:python"
