# vim: ts=2 sw=2 et

# On every push, and on every PR, do come checks.
#
# We do the following things:
# * Run CodeQL

name: Run CodeQL 

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  codeql:
    name: Run CodeQL on ubuntu-latest & Python 3.13
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - name: Install non-Python dependencies (Ubuntu)
      run: |
        true

    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install dependencies for testing
      run: |
        pip install .

    - name: CodeQL Init
      uses: github/codeql-action/init@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858
      with:
        languages: python

    - name: CodeQL Analyze
      uses: github/codeql-action/analyze@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858
      with:
        category: "/language:python"
