name: Docs

on:
  push:
    branches:
      - main1

jobs:
  # This job will eventually build the docs and deploy to GitHub Pages.
  # But for now, let's just get the build part working!
  docs:
    # A tip from https://github.com/marketplace/actions/deploy-to-github-pages
    # Make sure multiple docs builds aren't happening at the same time.
    concurrency: docs-${{ github.ref }}

    # Run this on Ubuntu
    runs-on: ubuntu-latest

    steps:
      # As always, start with a checkout.
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "code"

      # Bring in Python 3.9
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Install the package
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Build and install package
        run: |
          python -m pip install code

      # Build the docs with Sphinx.
      - name: Install Sphinx
        run: |
          python -m pip install code[docs]
      - name: Build docs
        run: |
          mkdir build
          sphinx-build -b html code/docs build

      # Upload the artifact.
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: "DocumentationHTML"
          path: "build"
