# vim: ts=2 sw=2 et

# On every push, and on every PR, do come checks.
#
# We do the following things:
# * Check for any no-commit things.

name: Check for no-commit flags

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  nocommit:
    name: Check No-commit
    runs-on: ubuntu-latest

    steps:
      # This is v4 of the action
    - name: Check out code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

    # This is v2 of the action
    - name: Check for N.O.C.O.M.M.I.T in the commits
      uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3
